version: '3'

services:
  app:
    image: ltstm-docker
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    env_file:
      - ../../.env
    ports:
      - "3030:3030"
    container_name: ltstm_frontend
    networks:
      - ltstm-api_backend-network

networks:
  ltstm-api_backend-network:
    external: true